name: Generate F-Droid repo

on: 
  repository_dispatch:
    types: [fdroid-update]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt update
          sudo apt install fdroidserver git-restore-mtime
          fdroid --version

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: git restore-mtime

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - name: Set git author
        run: |
          git config --global user.email "fdroid-bot@nym.com"
          git config --global user.name "nym-fdroid-bot"
          
      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0' 
        
      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
