name: Generate F-Droid repo

on:
  repository_dispatch:
    types: [fdroid-update]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-22.04

    steps:
      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt update
          sudo apt install git-lfs fdroidserver=2.1-1 git-restore-mtime
          fdroid --version

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
          fetch-depth: 0

      - name: List files
        run: ls -R .

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Configure git
        run: |
          # fix deprecation error
          git config --global alias.whatchanged "log --raw --no-merges"
          git config --global user.email "fdroid-bot@nym.com"
          git config --global user.name "nym-fdroid-bot"

      - name: Restore correct mtime
        run: git restore-mtime

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml
          chmod 0600 fdroid/keystore.p12
          chmod 0600 fdroid/config.yml

      - uses: actions/setup-go@v7
        name: Set up Go

      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f fdroid/keystore.p12 fdroid/config.yml
