name: Generate F-Droid repo

on:
  repository_dispatch:
    types: [fdroid-update]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install fdroidserver git-restore-mtime
          #brew install fdroidserver
          #brew install git-tools
          fdroid --version

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        timeout-minutes: 10
        with:
          ndk-version: r28c
          add-to-path: false

      - name: Verify NDK Setup
        run: |
          echo "NDK Path: ${{ steps.setup-ndk.outputs.ndk-path }}"
          if [ ! -d "${{ steps.setup-ndk.outputs.ndk-path }}" ]; then
            echo "Error: NDK directory not found at ${{ steps.setup-ndk.outputs.ndk-path }}"
            exit 1
          fi
          echo "NDK setup successful"
          ls -la "${{ steps.setup-ndk.outputs.ndk-path }}"

      - name: Set env
        shell: bash
        env:
          NIGHTLY_TIMESTAMP: ${{ inputs.nightly_timestamp }}
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "NDK_TOOLCHAIN_DIR=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: git restore-mtime

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - name: Set git author
        run: |
          git config --global user.email "fdroid-bot@nym.com"
          git config --global user.name "nym-fdroid-bot"

      - uses: actions/setup-go@v2
        name: Set up Go

      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
